### PR TITLE
Fix #67, #68, #71 (hopefully)

### LINKED ISSUE #67: Nonresponsive to login
I have tried removing and downloading the add-on in Firefox twice, and when I attempt to log in using my Pandora information, nothing happens. I can hit enter, the save button, there is no response. Not that an error was found in my username/password, that might actually be helpful. It just does nothing. This is using the up-to-date Firefox 88.0.1 browser.

### PR DESCRIPTION
**Pull request by hucario**
#67 should be fixed (added perms for hooking `onBeforeSendHeaders`, sets user-agent)
The way I fixed this should also fix main thread hangs due to synchronous requests. I had to edit a bunch of stuff across multiple files to get that to work.
#68 should be fixed due to the same changes that fix #67.
Additionally, I removed/replaced all references to jQuery in background files and `newpopup.js`, meaning that the only time jQuery is needed should be when you use the old player. Switching to `fetch` also resolves the warning for using sync xmlhttprequest on the main thread, so that's no longer going to show up on the extensions page.
#71 should be fixed due to switching to font icons instead of svg icons using the drop-shadow hack.
I don't have Firefox currently installed, so I can't test it, but I have a Good Feeling:tm: about it.

I also performed a few unrelated fixes / cleanups:
+ removed jquery from most of the code
+ changed buttons to actual `button` tags instead of `div`s for semantics
+ changed links to actual `a` links instead of divs with click listeners for `window.open` (which don't open into the same frame because I also put a `<base target="_blank">` on)
+ removed jquery from most of the code
+ made a windows port of `package.bash` for unpackaged/unzipped devving
+ removed units from `0` measurements because vscode kept bugging me
+ did I mention that I removed jquery from most of the code? pretty hyped about that
+ apparently album placeholder colors just... weren't being used, so I fixed that
+ there was a vertical separator missing between rows in the theming settings

please keep in mind that the commit messages were an afterthought and aren't grouped sensibly; sorry about that

### CODE REVIEW

**Comment by pvrs12** [comment]
This looks sick. I tested on Firefox and I believe it's working as expected. 

I'm noticing one small issue where pausing causes the Play button to disappear. It reappears after closing/re-opening the popup. I'll give it a look, but as you know my frontend knowledge... isn't

No jQuery 🦀 gang

**Comment by pvrs12** [comment]
Also, as for the commit messages, we can just squash it all down to one cool short one with a lot of 🦀 s

**Comment by hucario** [comment]
> I'm noticing one small issue where pausing causes the Play button to disappear. It reappears after closing/re-opening the popup

fixed

**Comment by hucario** [comment]
forgot to mention this earlier, but pandora's getStations endpoint apparently just... has an `additionalArt` parameter so anesidora now uses that to populate the station art initially
(also that typo is fixed in case the edit didn't give you a notification; I think we can merge now)

**Pull request merged**
