### PR TITLE
hotfix: missing tab buttons

### PR DESCRIPTION
**Pull request by hucario**
I was a bit too overzealous with deleting the old icons, and I forgot that `leftarrow.svg` & `rightarrow.svg` were still used. This commit puts those two specific files back.

### CODE REVIEW

**Comment by pvrs12** [comment]
Was just about to start looking into it, but you beat me to it! Ty for this

**Comment by pvrs12** [comment]
Apparently my squash broke it. It should be fixed now

**Comment by hucario** [comment]
yeah, was mildly confused by that lol and working on _another_ fix to try to get it to work
just installed latest, works fine

**Comment by pvrs12** [comment]
fantastic, i'll leave these to bake for a few days before i close issues.

Thank you again for all your help with this

**Pull request merged**
