### PR TITLE
V2 new player

### PR DESCRIPTION
**Pull request by pvrs12**
This has quite a few changes from @hucario and myself. Here is a non-exhaustive list:

- Brand new player with a much better visual design thanks to @hucario 
- Theming! @hucario 
- Improvements to history @hucario 
- A much better looking `options.htm` page @hucario
- Updated eslint compliance and standards
- Bugfixes for chrome options page (hotkeys, theming, etc)
- Bugfix for station change failing for the first song

### CODE REVIEW

**Comment by pvrs12** [comment]
@hucario This is getting towards ready. I've made a few changes to ensure that all of the code is consistent (I've always been a double quotes quy ¯\\\_(ツ)\_/¯).

There were some theming issues on Chrome for the options page, it didn't place nicely with the button color. What I've done for this is quickly detected if it's running on chrome and simply set `--color=auto` if that's the case. It ain't beautiful, but it is legible. The one exception to that is the Save button for which I've removed the `!important` tag. The consequence of which is a slightly less beautiful on firefox when a Light theme is used.

Additionally, I believe I've fixed the issues with the station list not loading the album art on the correct one. Some fancy hullabaloo with needing to know what the previous station was before changing the song. Not a huge issue in the end, but was funky to figure out.

Finally, I tested this on Android. It runs "fine" which is all it has ever done on Android. The larger UI makes button presses easier. It's not a market I'm particularly concerned about (sorry to all 46 of the android users...)

Are there any last changes you're hoping to slip into this before v2 @hucario? I've still got a few hours of work to do to update the store pages and screenshots for the application.

I'd also like to setup a theme repository and link to it on the Themes page, but that can be tossed in later.

**Comment by pvrs12** [comment]
https://pvrs12.github.io/AnesidoraThemes/
^ something like this, but ya know... better

**Comment by hucario** [comment]
Nice! Sorry I've taken so long to get to this.

> * Bugfix for station change failing for the first song

Oh! I didn't notice that, somehow.


[5e8a939:](https://github.com/pvrs12/Anesidora/pull/55/commits/5e8a939fee70b20af9ab9dfe9ab00e6f90dcb499)
> - Updated formatting to 4 spaces
> - Removed some trailing whitespace

Whoopsie. I must've missed a few tabs.
>  - Changed "images/New" to "images/new" to be consistent with other
 naming

Yeah, I thought I should change it but by that point it was already referenced in a lot of places, thanks.

> @hucario This is getting towards ready. I've made a few changes to ensure that all of the code is consistent (I've always been a double quotes quy ¯\_(ツ)_/¯).

What are you, a masochist? Having to press singlequote AND shift every time you open/close a string is fun for you? /s

> There were some theming issues on Chrome for the options page, it didn't place nicely with the button color. What I've done for this is quickly detected if it's running on chrome and simply set `--color=auto` if that's the case. It ain't beautiful, but it is legible. The one exception to that is the Save button for which I've removed the `!important` tag. The consequence of which is a slightly less beautiful on firefox when a Light theme is used.

Thanks - I don't use Chrome, so I also couldn't do anything about that. (I code on a computer with 2 gigs of ram, which means no linting and no Chrome. I code using what is effectively GNU Notepad, although it has syntax highlighting and bracket matching so that's pretty nice.)

> Additionally, I believe I've fixed the issues with the station list not loading the album art on the correct one. Some fancy hullabaloo with needing to know what the previous station was before changing the song. Not a huge issue in the end, but was funky to figure out.

Oh, I thought I fixed that. Thanks!

> Finally, I tested this on Android. It runs "fine" which is all it has ever done on Android. The larger UI makes button presses easier. It's not a market I'm particularly concerned about (sorry to all 46 of the android users...)

lol

> Are there any last changes you're hoping to slip into this before v2 @hucario? I've still got a few hours of work to do to update the store pages and screenshots for the application.

Not that I can think of, you've covered all the things I wasn't quite sure about.

> I'd also like to setup a theme repository and link to it on the Themes page, but that can be tossed in later.
> https://pvrs12.github.io/AnesidoraThemes/
> ^ something like this, but ya know... better

That looks fine. It performs its function well. I'll contribute some themes to that to help get it started.


also, a quick note:
image
quite the contrast there lol

**Comment by hucario** [comment]
Update:
uh-oh
image
turns out you can't just 'auto' text color if you don't also 'auto' background color. whoopsie.
working on a fix, one sec

**Comment by hucario** [comment]
This is the fix I've come up with:
```css
--color: white;
--button-color: black;
--background-color: #whatever-the-hex-code-is-I-forgot;
```

**Comment by pvrs12** [comment]
> What are you, a masochist? Having to press singlequote AND shift every time you open/close a string is fun for you? /s

I come from a Java/C++ background, it's habit... I'm also a masochist

> Thanks - I don't use Chrome, so I also couldn't do anything about that. (I code on a computer with 2 gigs of ram, which means no linting and no Chrome. I code using what is effectively GNU Notepad, although it has syntax highlighting and bracket matching so that's pretty nice.)

That's a heckin rig. Running vim?

> Oh, I thought I fixed that. Thanks!
I'm like 99% sure you did, and then I re-broke it as I was working on the not playing first song thing, so I had to fix it a different way

> quite the contrast there lol

gotta appeal to all the people

**Comment by hucario** [comment]
> > What are you, a masochist? Having to press singlequote AND shift every time you open/close a string is fun for you? /s
> 
> I come from a Java/C++ background, it's habit... I'm also a masochist

You have to be if you code Java.
> > Thanks - I don't use Chrome, so I also couldn't do anything about that. (I code on a computer with 2 gigs of ram, which means no linting and no Chrome. I code using what is effectively GNU Notepad, although it has syntax highlighting and bracket matching so that's pretty nice.)
> 
> That's a heckin rig. Running vim?

Nah, I literally use gedit w/ cobalt theme. 
https://wiki.gnome.org/Apps/Gedit
https://wiki.gnome.org/Projects/GtkSourceView/StyleSchemes?action=AttachFile&do=get&target=cobalt.png
(it looks better than the screenshot due to some customizations; once I get back on my regular machine I'll get you a screenshot of _my_ setup)
 
> > quite the contrast there lol
> 
> gotta appeal to all the people

:eyes:

**Comment by hucario** [comment]
I'm almost sorry.
image
Still "working" on fixing the options page btw.

**Comment by hucario** [comment]
Fixed, but I had to assassinate buttons CSS.
https://github.com/hucario/Anesidora/commit/736f2316ff66a0a2e63f009275a7937f8bc7d6f1

**Comment by pvrs12** [comment]
> Fixed, but I had to take out assassinate buttons CSS.

Looks great! Merged in.

With that... I _think_ we're ready to rock. I'll take some screenshots tomorrow probably


I also just want to log that my dream is that new themes are accessible from within Anesidora and it loads the list dynamically. It's very doable, but not worth it for this release.

**Comment by hucario** [comment]
I mean, it's possible, easily. I just don't like using GitHub as that.
I'll write it up and see if you want to use it.

oh, and here's that screenshot I said I'd get:
image

**Comment by pvrs12** [comment]
> I'll write it up and see if you want to use it.

Nah, don't worry about it. Like I said, something for the future to
consider. For now I think the theme repo is more than sufficient.

That's a pretty sick setup for such low system resources. Gotta avoid those
Electron apps at all costs.

**Comment by hucario** [comment]
```js
function f(url) {
	return new Promise((resolve) => {
		fetch(url).then((e) => {
			e.text().then(resolve);
		});
	});
}
f('https://raw.githubusercontent.com/pvrs12/AnesidoraThemes/master/ThemeList.md').then((d) => {
    var x = d.match(/#### [A-z \--`]*\n<a href="[A-z \--`]*"/g);
    x.forEach((e) => {
        console.log("https://pvrs12.github.io/AnesidoraThemes/" + e.match(/"[A-z \--`]*"/g)[0].substring(1).substring(0,e.match(/"[A-z \--`]*"/g)[0].substring(1).length-1));
    });
})
```
image

:thinking:

edit:
image
:thinking: :thinking: :thinking: :thinking: 

edit 2:
image
:thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: 

edit 3:
image
:thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: :thinking: 
(the name showing is a hover effect, just wasn't working because my screenshot software is weird. it's usually much easier to see)

**Comment by pvares** [comment]
Lol, well okay, guess it was pretty easy. I was going to add a `json` file with the name/reference

Something like:

```{
    "Aubergine": "https://pvrs12.github.io/AnesidoraThemes/themes/aubergine/aubergine.json",
    "Blue and Gold": "https://pvrs12.github.io/AnesidoraThemes/themes/blue_and_gold/blue_and_gold.json"
}```

Essentially the same thing you've done without the fancy regex

**Comment by pvrs12** [comment]
Whooopsie. Quick delete the comment from my work account

**Comment by hucario** [comment]
Alright, click events and generation are all set up.
It works!
Screenshot:
image
I still feel kinda bad using github pages for this but whatever

**Comment by hucario** [comment]
Adding some themes of mine

**Comment by hucario** [comment]
> > I'll write it up and see if you want to use it.
>
> Nah, don't worry about it. Like I said, something for the future to consider. For now I think the theme repo is more than sufficient. 

Whoops. Somehow I didn't see this before I went out and made it.

> That's a pretty sick setup for such low system resources. Gotta avoid those Electron apps at all costs.

Hey, I can run Discord native if I don't open any other apps, and that's Electron!
Seriously though, I've tried:
VSCode (freezes computer)
Brave (_almost_ freezes computer; it used to be my default browser so I had to rush and close my applications when I accidentally clicked a link outside of Firefox)
Light Table (freezes computer)
Atom (freezes computer)
I can run Github Desktop _and_ Firefox, although I can't open very many tabs if I do.

I'm happy I could even get syntax highlighting.
Eh, it fits my needs.
I really only use this computer to browse the web, code, do some image editing, at some point do homework, and mod Cave Story.

**Comment by pvrs12** [comment]
> Hey, I can run Discord native if I don't open any other apps, and that's Electron!


Ripcord! https://cancel.fm/ripcord/
Disclaimer, I haven't used it much for Discord, but it's been amazing for Slack and supposedly audio works with discord. No video, but if you're just chatting in channels then it should work perfectly

**Comment by hucario** [comment]
Ooo, looks great :D

**Comment by hucario** [comment]
Alright - I don't mean to hurry you, but what's the timeline for this?

Also, this screenshot on the Chrome web store seems a bit old lol
image

**Comment by pvrs12** [comment]
Soon ™️

But really, I'll see if I can get the screenshots grabbed today, maybe push
the update Monday or Tuesday.

**Comment by hucario** [comment]
nice

**Comment by pvrs12** [comment]
Release writeup/images are below. Anything you'd like me to add?


Version 2.0.0
================
Anesidora is now at version 2! Thanks to some huge contributions by [Hugh](https://github.com/hucario) the player has been fully redesigned with a new look and feel! Hugh also worked to add the option to theme the player so that you can customize it however you'd like. Of course if you're a fan of the original design, you can continue to use it the same way you always have.

Full update list:
- Player redesign [Hugh](https://github.com/hucario)
- Theming [Hugh](https://github.com/hucario)
- Theme builder [Hugh](https://github.com/hucario)
- Theme import/export [Hugh](https://github.com/hucario)
- Theme [repository](https://github.com/AnesidoraThemes)
- Fixed song history [Hugh](https://github.com/hucario)
- Added ability to Dislike from song History [Hugh](https://github.com/hucario)
- A dynamically updating Options page to preview size changes [Hugh](https://github.com/hucario)
- Several code quality changes to make future updates easier
- A few small tweaks to the Chrome options page due to limitations in Chrome

options
player
station_list
theming
history
login

**Comment by pvrs12** [comment]
Published on firefox and submitted for review on chrome!

**Comment by hucario** [comment]
:D

**Comment by hucario** [comment]
Haven't checked this for a bit, so didn't see that, sorry - all looks satisfactory :) :+1:

**Pull request merged**
