### PR TITLE
Fix accidental spamming of requests

### PR DESCRIPTION
**Pull request by hucario**

### CODE REVIEW

**Comment by hucario** [comment]
image
_look I see you laughing at my lack of explanation but it's four lines of edits and I already explained it in #84_

**Comment by lovelydumpling** [comment]
(lol I actually confused it for a smile/grin/happy emoji)
I am eagerly awaiting this update, really hoping it fixes my issues with the plugin.

**Comment by lovelydumpling** [comment]
Is there a chance we can get this fix before the (less than minor at this point) redesign is completed?

**Comment by hucario** [comment]
> Is there a chance we can get this fix before the (less than minor at this point) redesign is completed?

If you're asking whether it's also fixed on the redesign - yes. I fixed it on my PC first as I noticed it, then thought "yeah I should put this as a PR"
If you're asking to just push this as-is so that it's... you know... fixed, so you don't have to wait for the redesign- sure!

**Comment by lovelydumpling** [comment]
Installed (took me a bit to figure out how to package it but I did it), will update issue 76 tomorrow morning if this solved it :)
Edit: IT DID

**Pull request merged**
