### PR TITLE
fix #77, attempt fix #76

### LINKED ISSUE #76: Anedidora crashes after 2+ hours
@lovelydumpling lovelydumpling commented

```Version 2.1.2 working in Brave! Thanks a billion~

Edit: Whoops, nevermind. As of this morning it won't play music anymore. Just in Chrome, Firefox (v2.1) still working fine.

Edit 2: Firefox also broke. It seems after an hour or two, both will stop playing songs. Restarting the browser will allow them to play songs again.
```

@hucario hucario commented yesterday
```
That's very odd.

Well, I guess it's time for me to listen to anesidora for two hours to try to reproduce this. What a shame, I hate listening to music 😤
```

@lovelydumpling lovelydumpling commented 15 hours ago •
```
Sorry, I tend to listen to music for all-nighters due to my sleep habits, or occasionally when reading books/comics/manga. I've only produced it twice, once each. One with Brave overnight, the other with Firefox while reading manga. It seems at least if I'm not listening through such a long stretch, I can stop and start it up just fine. Makes me wonder if Pandora's original "Are you still listening?" behavior has anything to do with it.

Er, anyway, I'm off to bed again so I'll reply or edit this post in the morning whether it happened again on Brave.

EDIT: Yep sure enough as of this morning its broken again. So it does seem to be reproduceable on my end.
```

@hucario hucario commented 2 hours ago
```
The only thing I can think of is the callback arrays being a memory leak (whenever you re/open a popup, it adds a function to each array and if you open and close it a bunch it could be a leak? Maybe?) which would lag the player a ton. How does it stop working? Does it hang or crash?
```

Moved from #68

### LINKED ISSUE #77: In Chrome I can't sign in if I have this activated.
If I remove the new version, or I disable it, I can log in fine but if it is active I get an invalid password/email.  Took me 20 minutes of many tries until I narrowed it down.

Some reason this addon will not let me login either at Pandora.com OR using it to log in.

### PR DESCRIPTION
**Pull request by hucario**

### CODE REVIEW

**Comment by hucario** [comment]
oh alright it's just got all my other commits too


I only wanted those two latest ones but whatever

**Comment by pvrs12** [comment]
That's alright. I may need to cherrypick them to make it merge well though.

It's happening because of the squash&merge i did a few commits ago. Your repo is out of date with mine. You may need to do a `force` to get it back in sync.

**Comment by hucario** [comment]
pushed a commit that should fix #76 - edits partnerLogin to read this:

```js
async function partnerLogin() {
    if (localStorage.username !== "" && localStorage.password !== "") {
        let request = JSON.stringify({
            "username": "android",
            "password": "AC7IBG09A3DTSYM4R41UJWL07VLN8JI7",
            "version": "5",
            "deviceModel": "android-generic",
            "includeUrls": true
        });
        let response = await sendRequest(true, false, "auth.partnerLogin", request);
        var b = stringToBytes(decrypt(response.result.syncTime));
        // skip 4 bytes of garbage
        var s = "", i;
        for (i = 4; i < b.length; i++) {
            s += String.fromCharCode(b[i]);
        }
        syncTime = parseInt(s);
        clientStartTime = parseInt((new Date().getTime() + "").substr(0, 10));
        // if it didn't work we wouldn't be here so this wouldn't run. so, we're here and the login succeeded
	dontRetryPartnerLogin = false;
        return await userLogin(response);
    }
}
```

**Comment by hucario** [comment]
wait, I'm an idiot and I need to move that line to `userLogin`. Whoops

**Comment by hucario** [comment]
alright now it reads this in `userLogin`:
```js
    let res = await sendRequest(true, true, parameters, request);
    if (res.stat == "fail") {
        return "uncool credentials";
    }
    // we good apparently
	dontRetryPartnerLogin = false;

```

**Comment by hucario** [comment]
explanation of previous commit: 
because I made the handler an async function it would actually return a Promise instead of `false`
so instead I made it a synchronous function that executes an async function but doesn't wait and just returns false:
```js
async function doesntWorkAsHandler() {
   await etcetera();
   goToPlayerPaneOrSomething();
   return false;
} // returns a Promise that resolves to false
```
```js
function doesWork() {
    (async() => {
        await etcetera();
        goToPlayerPaneOrSomething();
    })();
    return false;
} // actually returns false

```

**Comment by hucario** [comment]
*previous commit doesn't exist, please don't realize I don't test nearly as much as I should

**Comment by pvrs12** [comment]
going to hold off on these for now. 

LMK when we're good to merge

**Comment by pvrs12** [comment]
https://github.com/pvrs12/Anesidora/pull/79
without any extras. will add more as you do 👉😎👉

**Comment by hucario** [comment]
think I'm ready now unless someone opens another issue

**Comment by pvrs12** [comment]
Fantastic! I'll be doing it under #79

**Pull request closed without merging**
